### ISSUE TITLE
json data incorrectly stringified causing GET with data/querystring to be result in bad url params

### ISSUE THREAD

**Issue by schmidlop** [frikille/promised-xhr#2]
```
var xhrOptions = {"method" : "GET",
    "data"   : {"param":"value"}
};
```

   return jXhr.send("http://example.org", xhrOptions);

results in a call to:
    http://example.org?0={&1=%22&2=p&3=a&4=r&5=a&6=m&7=%22&8=:&12=%22&13...

you get the idea...its treating the json string as an array of characters because it was string-ified [here](https://github.com/frikille/promised-xhr/blob/master/index.js#L165)

I believe the problem is the condition in line 164:

```
if (options.jsonContent !== false && 'data' in options) {
```

in my case `jsonContent` is undefined which is `!== false` and line 164 evaluates to true
maybe line 164 should read:

```
if (options.jsonContent && 'data' in options) {
```

not sure if that would fix it, could be that you should move the stringify to after you call `buildParamsAsQueryString`

**Comment by frikille** [comment]
Hey, yes, you're right, I missed this because there's a get function. But I've moved the json to string conversion before sending the request.
